# Generated by Django 5.0 on 2026-04-14 09:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название компании')),
                ('contact_person', models.CharField(max_length=100, verbose_name='Контактное лицо')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='Адрес')),
                ('inn', models.CharField(blank=True, max_length=12, verbose_name='ИНН')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('article', models.CharField(max_length=50, unique=True, verbose_name='Артикул')),
                ('category', models.CharField(choices=[('furniture_hardware', 'Фурнитура для корпусной мебели'), ('soft_furniture', 'Комплектующие для мягкой мебели'), ('materials', 'Материалы и полуфабрикаты'), ('fasteners', 'Крепёжные изделия'), ('profiles', 'Профильные изделия'), ('mattress', 'Матрасные комплектующие')], max_length=30, verbose_name='Категория')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('unit', models.CharField(default='шт.', max_length=20, verbose_name='Единица измерения')),
                ('in_stock', models.BooleanField(default=True, verbose_name='В наличии')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название сделки')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Сумма')),
                ('status', models.CharField(choices=[('new', 'Новая заявка'), ('processing', 'В обработке'), ('offer_sent', 'Отправлено КП'), ('negotiation', 'Согласование'), ('waiting_payment', 'Ожидание оплаты'), ('paid', 'Оплачена'), ('in_production', 'В производстве'), ('ready', 'Готова к отгрузке'), ('completed', 'Завершена'), ('cancelled', 'Отменена')], default='new', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('payment_reminder_count', models.IntegerField(default=0, verbose_name='Количество напоминаний об оплате')),
                ('max_payment_reminders', models.IntegerField(default=3, verbose_name='Максимум напоминаний')),
                ('expected_close_date', models.DateField(blank=True, null=True, verbose_name='Ожидаемая дата закрытия')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='crm.client', verbose_name='Клиент')),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_deals', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер')),
            ],
            options={
                'verbose_name': 'Сделка',
                'verbose_name_plural': 'Сделки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(choices=[('call_in', 'Входящий звонок'), ('call_out', 'Исходящий звонок'), ('email', 'Email'), ('meeting', 'Встреча'), ('note', 'Заметка'), ('whatsapp', 'WhatsApp'), ('telegram', 'Telegram')], max_length=20, verbose_name='Тип взаимодействия')),
                ('description', models.TextField(verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='crm.client', verbose_name='Клиент')),
                ('deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interactions', to='crm.deal', verbose_name='Сделка')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Менеджер')),
            ],
            options={
                'verbose_name': 'Взаимодействие',
                'verbose_name_plural': 'История взаимодействий',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DealProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Количество')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за единицу')),
                ('total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Итого')),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='crm.deal')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.product')),
            ],
            options={
                'verbose_name': 'Товар в сделке',
                'verbose_name_plural': 'Товары в сделке',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название задачи')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('priority', models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий'), ('urgent', 'Срочно')], default='medium', max_length=10, verbose_name='Приоритет')),
                ('due_date', models.DateTimeField(verbose_name='Срок выполнения')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Выполнена')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата выполнения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='crm.deal', verbose_name='Сделка')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ответственный')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
                'ordering': ['is_completed', 'due_date'],
            },
        ),
    ]
