# Generated by Django 5.0 on 2026-04-17 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_task_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='in_stock',
        ),
        migrations.AddField(
            model_name='product',
            name='quantity_in_stock',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Количество на складе'),
        ),
    ]
