# Generated by Django 5.0 on 2026-04-17 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_remove_product_in_stock_product_quantity_in_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity_in_stock',
        ),
        migrations.AddField(
            model_name='product',
            name='in_stock',
            field=models.BooleanField(default=True, editable=False, verbose_name='В наличии (быстрый доступ)'),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_quantity',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Укажите точное количество товара на складе.', max_digits=10, verbose_name='Количество на складе'),
        ),
    ]
